// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2855.cool2017.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc2855.cool2017.Robot;
import org.usfirst.frc2855.cool2017.RobotMap;

/**
 * default command for robot drive
 * polls continuously fetches values from joysticks
 * and uses them to drive robot
 */
public class mecanumdrive extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public mecanumdrive() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.drive.drivezRobot(-Robot.oi.getJoystick1().getX(), Robot.oi.getJoystick1().getY(), Robot.oi.getJoystick2().getX());
		SmartDashboard.putNumber("rear left vIn",RobotMap.driveleftfronttalon.getBusVoltage());
		SmartDashboard.putNumber("front left vIn",RobotMap.driveleftreartalon.getBusVoltage());
		SmartDashboard.putNumber("front right vIn",RobotMap.driverightfronttalon.getBusVoltage());
		SmartDashboard.putNumber("rear right vIn",RobotMap.driverightreartalon.getBusVoltage());
		SmartDashboard.putNumber("rear left 2 vIn", RobotMap.driveleftreartalon2.getBusVoltage());
		SmartDashboard.putNumber("rear right 2 vIn", RobotMap.driverightreartalon2.getBusVoltage());
		
    	SmartDashboard.putNumber("rear left vOut",RobotMap.driveleftfronttalon.getOutputVoltage());
		SmartDashboard.putNumber("front left vOut",RobotMap.driveleftreartalon.getOutputVoltage());
		SmartDashboard.putNumber("front right vOut",RobotMap.driverightfronttalon.getOutputVoltage());
		SmartDashboard.putNumber("rear right vOut",RobotMap.driverightreartalon.getOutputVoltage());
		SmartDashboard.putNumber("rear left 2 vOut", RobotMap.driveleftreartalon2.getOutputVoltage());
		SmartDashboard.putNumber("rear right 2 vOut", RobotMap.driverightreartalon2.getOutputVoltage());
		
		SmartDashboard.putNumber("rear left aOut",RobotMap.driveleftfronttalon.getOutputCurrent());
		SmartDashboard.putNumber("front left aOut",RobotMap.driveleftreartalon.getOutputCurrent());
		SmartDashboard.putNumber("front right aOut",RobotMap.driverightfronttalon.getOutputCurrent());
		SmartDashboard.putNumber("rear right aOut",RobotMap.driverightreartalon.getOutputCurrent());
		SmartDashboard.putNumber("rear left 2 aOut", RobotMap.driveleftreartalon2.getOutputCurrent());
		SmartDashboard.putNumber("rear right 2 aOut", RobotMap.driverightreartalon2.getOutputCurrent());
		
		SmartDashboard.putNumber("rear left Temp (C)",RobotMap.driveleftfronttalon.getTemperature());
		SmartDashboard.putNumber("front left Temp (C)",RobotMap.driveleftreartalon.getTemperature());
		SmartDashboard.putNumber("front right Temp (C)",RobotMap.driverightfronttalon.getTemperature());
		SmartDashboard.putNumber("rear right Temp (C)",RobotMap.driverightreartalon.getTemperature());
		SmartDashboard.putNumber("rear left 2 Temp (C)", RobotMap.driveleftreartalon2.getTemperature());
		SmartDashboard.putNumber("rear right 2 Temp (C)", RobotMap.driverightreartalon2.getTemperature());
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
