// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2855.cool2017;

import edu.wpi.first.wpilibj.BuiltInAccelerometer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController ballintakeintaketalon;
    public static CANTalon shootershootertalon;
    public static CANTalon driveleftreartalon;
    public static CANTalon driveleftreartalon2;
    public static CANTalon driveleftfronttalon;
    public static CANTalon driverightfronttalon;
    public static CANTalon driverightreartalon;
    public static CANTalon driverightreartalon2;
    public static RobotDrive2855 driveRobotDrive41;
    public static SpeedController climbingarmclimbingmotor;
    public static SpeedController gearthingygearmotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController agitator;
    public static BuiltInAccelerometer accelerometer;
    public static CameraServer camera;
    public static edu.wpi.first.wpilibj.Ultrasonic Ultrasonic;
    public static void init() {
    	CameraServer.getInstance().startAutomaticCapture();
        agitator = new Talon(4);
        LiveWindow.addActuator("agitator", "agitator", (Talon) agitator);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        ballintakeintaketalon = new Talon(5);
        LiveWindow.addActuator("ball intake", "intake talon", (Talon) ballintakeintaketalon);
        
        shootershootertalon = new CANTalon(7);
        LiveWindow.addActuator("shooter", "shooter talon", shootershootertalon);
        
        driveleftreartalon = new CANTalon(4);
        LiveWindow.addActuator("drive", "left rear talon", driveleftreartalon);
        
        driveleftreartalon2 = new CANTalon(1);
        LiveWindow.addActuator("drive", "left rear talon2", driveleftreartalon2);
        
        driveleftfronttalon = new CANTalon(5);
        LiveWindow.addActuator("drive", "left front talon", driveleftfronttalon);
        
        driverightfronttalon = new CANTalon(8);
        LiveWindow.addActuator("drive", "right front talon", driverightfronttalon);
        
        driverightreartalon = new CANTalon(6);
        LiveWindow.addActuator("drive", "right rear talon", driverightreartalon);
       
        driverightreartalon2 = new CANTalon(0);
        LiveWindow.addActuator("drive", "right rear talon2", driverightreartalon2);
        
        driveRobotDrive41 = new RobotDrive2855(driveleftfronttalon, driveleftreartalon,
              driverightfronttalon, driverightreartalon, driverightreartalon2, driverightreartalon2);
        
        driveRobotDrive41.setSafetyEnabled(true);
        driveRobotDrive41.setExpiration(0.1);
        driveRobotDrive41.setSensitivity(0.5);
        driveRobotDrive41.setMaxOutput(1.0);

        driveRobotDrive41.setInvertedMotor(RobotDrive2855.MotorType.kFrontRight, true);
        driveRobotDrive41.setInvertedMotor(RobotDrive2855.MotorType.kFrontLeft, true);
        climbingarmclimbingmotor = new Talon(6);
        LiveWindow.addActuator("climbing arm", "climbing motor", (Talon) climbingarmclimbingmotor);
        
        gearthingygearmotor = new Spark(1);
        LiveWindow.addActuator("Gear thingy", "gear motor", (Spark) gearthingygearmotor);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        Ultrasonic = new edu.wpi.first.wpilibj.Ultrasonic(8, 9);
        

        
    }
}
